### ISSUE TITLE
[security] vulnerable to length extension attack

### ISSUE THREAD

**Issue by zzh1996** [zhoilet/Password#1]
once a salt and password pair is leaked, other passwords with the leaked salt as prefix can be easily calculated.

example:
if salt=github&password=blabla is leaked, the password of salt=github2 can be calculated.

fix:
use sha256(salt+key), not sha256(key+salt)

**Comment by zhoilet** [comment]
"if salt=github&password=blabla is leaked, the password of salt=github2 can be calculated."

How can password of salt=github2 be calculated?

**Comment by zhoilet** [comment]
I have discussed with Zihan. The results are shown as below.

First of all, the point is very good. I really appreciate it. Length extension attack does bring possible risk in theory.

```
password = ""
for index in range(0, passwordLength):
	beginPosition = index * oneGroupLength
	endPosition = (index + 1) * oneGroupLength
	value = int(hash_string[beginPosition : endPosition], 16)
	password += characterSet[value % len(characterSet)]
```

Since we discard information in password generation step. It is hard to get hash_string from generated password. For example, if user use salt "12Exxx", then oneGroupLength=5, for a given password there are about (16^5/100)^12 * 16^4 possible hash_strings. This is a very large number. Therefore we believe the algorithm is still secure. 

Consider that the modify of hash method (from sha256(salt+sha256(key)) to sha256(sha256(key)+salt)) will change all of user's previous passwords, we decide **not to** modify hash algorithm now. 

Thank Zihan again for offering help!
